name: "Cway MCP Server"
description: "Production-ready Model Context Protocol server for Cway GraphQL API integration"
version: "0.1.0"
author: "Fredrik Hultin"

# Project metadata
project:
  type: "fullstack"
  technologies:
    - "Python 3.11"
    - "TypeScript"
    - "React 19"
    - "MCP Framework"
    - "GraphQL"
    - "WebSocket"
  
# IDE configuration
ide:
  recommended_extensions:
    vscode:
      - "ms-python.python"
      - "bradlc.vscode-tailwindcss"
      - "esbenp.prettier-vscode"
      - "ms-python.black-formatter"
    warp:
      - "python"
      - "typescript"
      - "react"

# Development environment
environment:
  python_version: "3.11"
  node_version: "18"
  virtual_env: "venv"
  package_managers:
    - "pip"
    - "npm"

# Quick actions
quick_actions:
  - name: "🚀 Start Full Stack"
    description: "Launch both server and dashboard"
    command: |
      source venv/bin/activate
      cd server && python main.py --mode dashboard &
      cd client && npm start
    
  - name: "🧪 Run All Tests"
    description: "Execute comprehensive test suite"
    command: |
      source venv/bin/activate
      cd server && python -m pytest tests/ -v --cov=src
      cd client && npm test -- --watchAll=false
    
  - name: "🔧 Setup Project"
    description: "Complete project initialization"
    command: |
      python -m venv venv
      source venv/bin/activate
      cd server && pip install -r requirements.txt
      cd ../client && npm install
      cp .env.example server/.env
      echo "✅ Project setup complete! Edit server/.env with your Cway API token."

# Bookmarks for important files
bookmarks:
  - name: "Server Entry Point"
    path: "server/main.py"
    description: "Main server launcher"
  - name: "MCP Server Implementation"
    path: "server/src/presentation/cway_mcp_server.py" 
    description: "Core MCP server logic"
  - name: "Dashboard Component"
    path: "client/src/components/SimpleDashboard.tsx"
    description: "Main dashboard component"
  - name: "Environment Template"
    path: ".env.example"
    description: "Environment variables template"
  - name: "Server Configuration"
    path: "server/config/settings.py"
    description: "Server configuration management"

# Development workflows
workflows:
  development:
    setup:
      - "Create virtual environment"
      - "Install Python dependencies"
      - "Install Node.js dependencies"
      - "Copy environment template"
      - "Configure Cway API token"
    
    daily:
      - "Activate virtual environment"
      - "Start server with dashboard"
      - "Start React client"
      - "Begin development"
    
    testing:
      - "Run unit tests"
      - "Run integration tests"
      - "Check code coverage"
      - "Lint and format code"
    
    deployment:
      - "Run comprehensive tests"
      - "Build production client"
      - "Create Docker image"
      - "Deploy to environment"

# Status indicators
status:
  build: "passing"
  tests: "95% coverage"
  dependencies: "up-to-date"
  documentation: "comprehensive"